version: '3'
services:
  # backend:
  #   build: 
  #     context: ../
  #     dockerfile: docker/Dockerfile.production 
  #     args:
  #       port: ${PORT}
  #   env_file:
  #     - ../.env
  #   restart: always
  #   ports:
  #     - "${PORT}:${PORT}"
  #   environment:
  #     WAIT_HOSTS: database:27017
  database:
    image: mongo
    env_file:
      - .env
    volumes:
      - ".${MONGO_DATA_DIR}:${MONGO_DATA_DIR}"
    expose:
      - 27017
    command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ~/logs/:/usr/src/app/logs/
    links:
      - database
    depends_on:
      - database
  frontend:
    build: 
      context: ./frontend/
    ports:
     - "5006:80"
    links:
      - backend
    restart: always
    volumes: 
      - ./frontend/pdf:/usr/src/app/pdf/
    #   - ./frontend/images:/usr/src/app/images/